### ISSUE TITLE
Downloads appear hosed

### ISSUE THREAD

**Issue by buggtb** [SatelliteApplicationsCatapult/sedas_pyapi#26]
Any download operation seems to not work with the latest build from pypi

If I just run the bulk_downloader is just loops saying:

```
INFO:bulk_downloader:3 active threads, 0 restarted.
DEBUG:bulk_downloader:checking state of request 54922 for S1B_IW_SLC__1SDV_20190512T061418_20190512T061445_016207_01E806_FC47
DEBUG:bulk_downloader:checking state of request 54923 for S1A_IW_SLC__1SDV_20190511T062300_20190511T062327_027176_03103D_DBA6
DEBUG:bulk_downloader:checking state of request 54924 for S1A_IW_SLC__1SDV_20190509T174940_20190509T175008_027154_030F96_D9CB
DEBUG:bulk_downloader:checking state of request 54925 for S1B_IW_SLC__1SDV_20190508T175659_20190508T175727_016156_01E65D_67EB
DEBUG:bulk_downloader:checking state of request 54926 for S1A_IW_SLC__1SDV_20190506T061505_20190506T061532_027103_030DED_DE60
DEBUG:bulk_downloader:checking state of request 54927 for S1A_IW_SLC__1SDV_20190506T061440_20190506T061507_027103_030DED_5C99
DEBUG:bulk_downloader:checking state of request 54928 for S1B_IW_SLC__1SDV_20190503T174852_20190503T174920_016083_01E406_4385
DEBUG:bulk_downloader:checking state of request 54929 for S1A_IW_SLC__1SDV_20190502T175752_20190502T175820_027052_030C11_8F59
DEBUG:bulk_downloader:checking state of request 54930 for S1B_IW_SLC__1SDV_20190430T061417_20190430T061444_016032_01E25F_BDDF
INFO:bulk_downloader:0 downloads pending, 0 downloads in progress, 9 requests pending
```

The bulkdownloader in the sample just sits there doing nothing and another complains its missing the productURL key. Has the api changed?

**Comment by anthony-scarth** [comment]
Hi! I'm not experienced with the API, but https://geobrowser.satapps.org reports that there are ongoing issues with retrieving archived products (older than 90 days). As all of your products listed are older than this, it's possible that they are just stuck in the process that makes them available for download, and this is why the script is seemingly not doing anything.

**Comment by emilyselwood** [comment]
Hi @buggtb and @anthony-scarth 

There are currently problems with the Long term archive requests not completing. Tom the Debug output you are seeing is showing that the requests are currently pending and it is waiting for them to complete, which is what it should be doing. I'm not sure if a time out is a good idea. There is a level of long term archive which goes to one of those big tape archive robot things, which can take a really long time (hours) to respond.

While this isn't a problem with the API client I'll drop an update here if/ when I hear something.

**Comment by amanshu** [comment]
Hi @buggtb and @anthony-scarth,

We've now resolved the issues with the Long Term Archive, and the system is working its way through the backlog of requests.  Unfortunately this appears to be quite a long list and will take a while to download.  Hopefully your data will be available as soon as possible.
