### ISSUE TITLE
Attempting to download any product results in HTTP Error 500

### ISSUE THREAD

**Issue by anthony-scarth** [SatelliteApplicationsCatapult/sedas_pyapi#27]
Hi! I am attempting to use this library, but any download that I attempt results in HTTP Error 500.

I have even duplicated the example code (updating the product to one within the 90 day window)

`sedas = SeDASAPI(username,password)`
`singleProduct = sedas.search_product("S1A_IW_GRDH_1SDV_20190901T063117_20190901T063142_028824_034401_BA52")`
`sedas.download(singleProduct[0], "~/S1A_IW_GRDH_1SDV_20190901T063117_20190901T063142_028824_034401_BA52.zip")`

The search request authenticates correctly and returns a product, but the download crashes and returns the following (as text):

![image](https://user-images.githubusercontent.com/46593983/64544018-27b28000-d31e-11e9-995f-eaaca1580c21.png)

This is also the case for running bulk downloads.

Can you please help me work out what could be happening here?

**Comment by emilyselwood** [comment]
Hi @anthony-scarth Thank you for letting me know about this. The firewall that guards the SeDAS system gets cranky if requests don't have a user-agent header. I've created a fix which I'm just waiting for a review of.

**Comment by emilyselwood** [comment]
@anthony-scarth Just to let you know I've now pushed a new version. 0.4.2 on pypi should have the user agent fix. Any problem please let me know.

**Comment by anthony-scarth** [comment]
@emilyselwood Works perfectly. Thank you very much
