### ISSUE TITLE
downloadUrl missing, bulk download not working

### ISSUE THREAD

**Issue by david-tmotus** [SatelliteApplicationsCatapult/sedas_pyapi#35]
Hi,
I am following the example "Bulk download many products" and the process is in stand by, waiting for the next product to download. But looking to the list of products that I have in my "result_sar['products']" I can only see that the first product has the key "downloadUrl", the rest of the products don't have this key, and I think this is the reason why the SeDASBulkDownload is doing nothing. 
I attached the python file and the sample.json as txt.

[downloader.txt](https://github.com/SatelliteApplicationsCatapult/sedas_pyapi/files/4770078/downloader.txt)
[Sample.txt](https://github.com/SatelliteApplicationsCatapult/sedas_pyapi/files/4770079/Sample.txt)

**Comment by emilyselwood** [comment]
Hi @david-tmotus 
This is as expected. The API does not give us a download URL when a long term archive request is required. 

The bulk download class will take care of those for you, however they can take sometime to complete, in the order of hours. If you turn up logging to debug on the "sedas_pyapi" you will see more information about its progress. We don't normally log at that level as it is a lot of information.
